### PR TITLE
Fix empty decision cell

### LINKED ISSUE #1102: Bug - empty decision cell

### PR DESCRIPTION
**Pull request by Omri-Levy**
### Description
UI prior to this change (double grey separator):
image

### CODE REVIEW

File: apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx [hunk 1]
```diff
@@ -221,6 +221,20 @@ export const useTasks = ({
           ],
         };
 
+        const decisionCell = {
+          type: 'details',
+          value: {
+            id,
+            title: 'Decision',
+            hideSeparator: true,
+            data: decision?.status
```
Comment (Omri-Levy) [inline apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx:230]: Addresses the side-effect of canceling "Re-uploaded needed" where `decision` exists with a `status` of `null`.

File: apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx [hunk 2]
```diff
@@ -270,18 +284,7 @@ export const useTasks = ({
...
-                id,
-                title: 'Decision',
-                hideSeparator: true,
-                data: Object.entries(decision ?? {}).map(([title, value]) => ({
-                  title,
-                  value,
-                })),
-              },
-            },
+            decisionCell,
```
Comment (Omri-Levy) [inline apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx:287]: No change in data, just extracted to variable to make the cell easier to find.

**Review by alonp99 — APPROVED** [review]
