### PR TITLE
blokh/feat/ (fix-badges & intial states in DB)

### LINKED ISSUE #1222: (fix-badges & intial states in DB)

### LINKED ISSUE #1252: fix-badges & intial states of defintion when starting instance

### PR DESCRIPTION
**Pull request by Blokh**
- [x] added tags on missing workflows
- [x] updates workflow service to set state and initial state in DB
- [x] add tags logic on created workflow

### CODE REVIEW

**Review by tomer-shvadron — APPROVED** [review]

File: apps/backoffice-v2/src/pages/Entity/components/Case/hooks/useCaseActionsLogic/useCaseActionsLogic.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const useCaseActionsLogic = ({ workflowId, fullName }: IUseActions) => {
   );
 
   const tag = useMemo(() => {
-    if (!workflow?.context?.entity?.data?.__isFinished) {
+    if (workflow?.context?.entity?.data?.__isFinished === false) {
```
Comment (Blokh) [inline apps/backoffice-v2/src/pages/Entity/components/Case/hooks/useCaseActionsLogic/useCaseActionsLogic.tsx]: this is being removed

File: services/workflows-service/scripts/generate-end-user.ts [hunk 2]
```diff
@@ -132,6 +132,7 @@ export const generateBusiness = ({
         workflowDefinitionId,
         createdAt: faker.date.recent(2),
         projectId: projectId,
+        tags: ['manual_review'],
```
Comment (Omri-Levy) [inline services/workflows-service/scripts/generate-end-user.ts]: Should get the tag configured to the initial state, if not we should still use the tags enum here.

File: services/workflows-service/scripts/workflows/kyc-email-process-example.ts [hunk 3]
```diff
@@ -13,6 +13,7 @@ export const kycEmailSessionDefinition = {
     initial: 'idle',
     states: {
       idle: {
+        tags: [StateTag.PENDING_PROCESS],
```
Comment (Omri-Levy) [inline services/workflows-service/scripts/workflows/kyc-email-process-example.ts:16]: `PENDING_PROCESS` signifies an in-progress process with a vendor. Is that the case for `idle`?

File: services/workflows-service/scripts/workflows/parent-kyb-kyc-session-workflow.ts [hunk 4]
```diff
@@ -135,19 +136,22 @@ export const parentKybWithSessionWorkflowDefinition = {
...
       run_kyb_enrichment: {
+        tags: [StateTag.COLLECTION_FLOW],
         on: {
           KYB_DONE: [{ target: 'pending_kyc_response_to_finish' }],
           // TODO: add 404 handling
           FAILED: [{ target: 'auto_reject' }],
         },
       },
       pending_kyc_response_to_finish: {
+        tags: [StateTag.COLLECTION_FLOW],
```
Comment (Omri-Levy) [inline services/workflows-service/scripts/workflows/parent-kyb-kyc-session-workflow.ts]: Doesn't this step waits for a vedor process to be done?

File: services/workflows-service/src/workflow/workflow.service.ts [hunk 5]
```diff
@@ -1386,6 +1385,8 @@ export class WorkflowService {
             } as InputJsonValue,
             config: merge(workflowDefinition.config, validatedConfig || {}) as InputJsonValue,
             status: 'active',
+            state: workflowDefinition.definition.initial,
```
Comment (Omri-Levy) [inline services/workflows-service/src/workflow/workflow.service.ts:1388]: If makes sense, running the machine and getting the current state will be more reliable. Would give access to the current tag, too.

Comment (Omri-Levy) [reply services/workflows-service/src/workflow/workflow.service.ts:1388]: Let's make sure we're not missing other instances of `workflowRuntimeDataRepository.create`.

File: services/workflows-service/scripts/workflows/kyc-email-process-example.ts (hunk 3 above)
Comment (Blokh) [reply services/workflows-service/scripts/workflows/kyc-email-process-example.ts:16]: in this context, the StateTag.PENDING_PROCESS of end user over KYC session ( this state is pending for getting kyc session )

File: services/workflows-service/src/workflow/workflow.service.ts (hunk 5 above)
Comment (Blokh) [reply services/workflows-service/src/workflow/workflow.service.ts:1388]: true, but the change is quite scary - I wanted to fix it here without changing the logic.
so, if we want to run the machine when creating it. we need to re-validate that all the schemas are valid from the get-go

File: services/workflows-service/scripts/workflows/kyc-email-process-example.ts (hunk 3 above)
Comment (Omri-Levy) [reply services/workflows-service/scripts/workflows/kyc-email-process-example.ts:16]: But is it pending a response from a 3rd party?

File: services/workflows-service/src/workflow/workflow.service.ts (hunk 5 above)
Comment (Omri-Levy) [reply services/workflows-service/src/workflow/workflow.service.ts:1388]: Alright, let's just make sure it's documented somewhere. It could be a good candidate for Prisma middleware too. 🙂

File: services/workflows-service/scripts/generate-end-user.ts [hunk 6]
```diff
@@ -188,6 +190,7 @@ export const generateEndUser = ({
           createdAt: faker.date.recent(2),
           projectId: projectId,
           parentRuntimeDataId: workflow.parentRuntimeId,
+          tags: StateTag.MANUAL_REVIEW,
```
Comment (Omri-Levy) [inline services/workflows-service/scripts/generate-end-user.ts]: Missing square brackets.

**Review by alonp99 — APPROVED** [review]
