### PR TITLE
Hide registry data when OpenCorporates failed

### LINKED ISSUE #965: Hide registry data when OpenCorporates failed

### PR DESCRIPTION
**Pull request by MatanYadaev**
Closes #965

### CODE REVIEW

File: apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx [hunk 1]
```diff
@@ -72,7 +72,10 @@ export const useTasks = ({
     Object.keys(pluginsOutput ?? {}).length === 0
       ? []
       : pluginsOutputKeys
-          ?.filter(key => !!Object.keys(pluginsOutput[key] ?? {})?.length)
+          ?.filter(
+            key =>
+              !!Object.keys(pluginsOutput[key] ?? {})?.length && !('error' in pluginsOutput[key]),
+          )
```
Comment (MatanYadaev) [inline apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx:78]: This is the only change that is relevant to the task. The rest is boyscouting.

File: services/workflows-service/scripts/workflows/kyc-email-process-example.ts [hunk 2]
```diff
@@ -63,7 +63,7 @@ export const kycEmailSessionDefinition = {
       {
         name: 'kyc_session',
         pluginKind: 'kyc-session',
-        url: `{secret.KYC_API_URL}/individual-verification-sessions`,
+        url: `${env.UNIFIED_API_URL}/individual-verification-sessions`,
```
Comment (Blokh) [inline services/workflows-service/scripts/workflows/kyc-email-process-example.ts:66]: please validate that it's set in hashicorp and delete all KYC API URL and KYB API URL from all vaults please

Comment (MatanYadaev) [reply services/workflows-service/scripts/workflows/kyc-email-process-example.ts:66]: I will delete the other vars only when it will be merged to prod
