### PR TITLE
Fix backoffice images in environments without signed url setup

### LINKED ISSUE #1200: [BAL-298] Fix backoffice images in environments without signed url setup
null

<sub>[BAL-298](https://linear.app/ballerine/issue/BAL-298/fix-backoffice-images-in-environments-without-signed-url-setup)</sub>

### PR DESCRIPTION
**Pull request by alonp99**

### CODE REVIEW

**Review by tomer-shvadron — APPROVED** [review]

File: apps/backoffice-v2/src/domains/storage/fetchers.ts [hunk 1]
```diff
@@ -39,7 +37,7 @@ export const fetchFileInfoById = async (fileId: string) => {
 };
 export const fetchFileById = async (fileId: string) => {
   const fileInfo = await fetchFileInfoById(fileId);
-  if (fileInfo.fileNameInBucket) {
+  if (fileInfo.fileNameInBucket && import.meta.env.VITE_FETCH_SIGNED_URL === 'TRUE') {
```
Comment (Omri-Levy) [inline apps/backoffice-v2/src/domains/storage/fetchers.ts:40]: Is this intentional? (all caps)

Comment (Blokh) [reply apps/backoffice-v2/src/domains/storage/fetchers.ts:40]: by default it's true i think lowercased. it should be downcased

Comment (Blokh) [reply apps/backoffice-v2/src/domains/storage/fetchers.ts:40]: yes it is uppercased by default
