### PR TITLE
Fix backoffice UI empty states

### LINKED ISSUE #1187: Add UI fallback to the backoffice for missing data
- [x] Display a fallback for missing entity name in the cases list items
- [x] Display a fallback for invalid blocks
- [ ] Display a fallback badge(?)

### PR DESCRIPTION
**Pull request by Omri-Levy**
- [x] No longer rendering nothing when entity name is missing
- [x] No longer rendering nothing when no tasks are available

image
image

### CODE REVIEW

File: apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx [hunk 1]
```diff
@@ -317,99 +317,103 @@ export const useTasks = ({
...
+                    },
+                  ],
+                },
+              ],
+          },
+        ];
 
   return useMemo(() => {
-    return entity ? [entityInfoBlock, ...registryInfoBlock, ...taskBlocks, mapBlock] : [];
+    return entity ? [...entityInfoBlock, ...registryInfoBlock, ...taskBlocks, ...mapBlock] : [];
```
Comment (Omri-Levy) [inline apps/backoffice-v2/src/pages/Entity/hooks/useTasks/useTasks.tsx:416]: Making sure there are no empty objects in this array. This case is spreading an empty array.

**Review by tomer-shvadron — APPROVED** [review]

**Review by alonp99 — APPROVED** [review]
